services:
  - type: web
    name: ftfr-sla-dashboard
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DASHBOARD_PASSWORD
        value: Mindray99!
      - key: NODE_VERSION
        value: 18.20.4
